### ISSUE TITLE
Can we please sort the list in alphabetical order?

### ISSUE THREAD

**Issue by iadeelzafar** [Pitt-CSC/Summer2021-Internships#116]

**Comment by aidev1065** [comment]
I personally like this layout because it's easier to see when new internships get added

**Comment by zejunliu** [comment]
Didn’t we vote before? Most people go with the current sorting method?

**Comment by iadeelzafar** [comment]
If this is a duplicate issue, feel free to close.

**Comment by Zmwang622** [comment]
Yup we've talked about this before. #10 

If you want easy searching use Ctrl+F I guess
