### ISSUE TITLE
Hewlett Packard Enterprise

### ISSUE THREAD

**Issue by tuankiet65** [Pitt-CSC/Summer2021-Internships#118]
Software Developer Intern: https://careers.hpe.com/job/Hewlett-Packard-Enterprise-San-Jose-California/118653859
Software Engineering Intern: https://careers.hpe.com/job/Hewlett-Packard-Enterprise-Houston-Texas/118653867

~~I wonder what's the difference between these posting apart from the location.~~ The Software Engineering one is for Purdue students only:

> Hewlett Packard Enterprise is seeking a highly motivated Software Engineering Intern. This is a unique internship for **current Purdue students** as it is full-time over the summer working for Hewlett Packard Enterprise at the Houston, TX location and continues part-time (10-20 hours a week) during the school year on Purdue’s campus (West Lafayette, IN) while you continue your degree.

**Comment by Zmwang622** [comment]
yeah gonna close bc its for purdue students only

**Comment by tuankiet65** [comment]
The Software Development Intern is not though, I first came across it at my college's career portal.
