### ISSUE TITLE
Google Link broken?

### ISSUE THREAD

**Issue by CookieComputing** [Pitt-CSC/Summer2021-Internships#120]
It looks like Google closed their app for the link provided in the sheet... anyone else see this?

**Comment by dragonejt** [comment]
Yeah, the application was due today. It's probably already too late. Good luck with your other applications and apply early (NOW).

**Comment by CookieComputing** [comment]
Ah, that explains it (I've already applied a while ago). Do you happen to know if people are hearing back?

**Comment by dragonejt** [comment]
Not sure. I applied on Friday and have not heard back. You may want to ask in r/CsMajors.

**Comment by zejunliu** [comment]
I know some people already finished OA.
