### ISSUE TITLE
Possible Inclusion of Date

### ISSUE THREAD

**Issue by ateniolatobi** [Pitt-CSC/Summer2021-Internships#138]
First, I want to thank you guys for creating this repo. I've found it great and important in my search for an Internship. 
I wanted to ask if as an Improvement, the date when the links came out can be included so students can have a sense of how early they are in their application. 
Once again, Thanks a lot.

**Comment by Zmwang622** [comment]
Dates are included on the Google Sheet: https://docs.google.com/spreadsheets/d/1bJq7YQV19TWyzPCBeQi5P4uOm8uiAAm2AHCnVNGRIDg/edit#gid=0
