### ISSUE TITLE
New Google internship openings

### ISSUE THREAD

**Issue by shazil-arif** [Pitt-CSC/Summer2021-Internships#191]
Looks like Google is open again with multiple new internship positions. Update Google to Open status from Closed

[See here](https://careers.google.com/jobs/results/?category=DATA_CENTER_OPERATIONS&category=DEVELOPER_RELATIONS&category=HARDWARE_ENGINEERING&category=INFORMATION_TECHNOLOGY&category=MANUFACTURING_SUPPLY_CHAIN&category=NETWORK_ENGINEERING&category=PRODUCT_MANAGEMENT&category=PROGRAM_MANAGEMENT&category=SOFTWARE_ENGINEERING&category=TECHNICAL_INFRASTRUCTURE_ENGINEERING&category=TECHNICAL_SOLUTIONS&category=TECHNICAL_WRITING&company=Google&company=YouTube&employment_type=INTERN&location=United%20States&q=)

**Comment by Zmwang622** [comment]
wanna link them?

**Comment by Zmwang622** [comment]
oh you did link them my bad LOL
