### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by Egahi** [Pitt-CSC/Summer2021-Internships#224]
2021 University Application (Interns and New grads)
https://urapplication2021.splashthat.com/

Locations
1. Japan and Asia Pacific regions
2. North and Latin America regions
3. Europe, Middle East, and Africa regions

**Comment by Egahi** [comment]
No shout out?

**Comment by Zmwang622** [comment]
I was gonna give you one but if you're gonna be rude like that idk if i should....
