### ISSUE TITLE
SAP job is filled

### ISSUE THREAD

**Issue by michaelghuang19** [Pitt-CSC/Summer2021-Internships#24]
The link for SAP provides the following info:

"
SAP Intern - Mobile Job
Date: Jul 8, 2020

Company: SAP

Sorry, this position has been filled.
"

**Comment by gregordr** [comment]
Does anyone else notice how quickly positions are getting filled this summer? I have seen positions disappear from listings within 16 hours.

**Comment by fayedraza** [comment]
> Does anyone else notice how quickly positions are getting filled this summer? I have seen positions disappear from listings within 16 hours.

Yea, I know right. I was gonna apply and then it says applications are closed.
