### ISSUE TITLE
Vanguard position is for summer 2020

### ISSUE THREAD

**Issue by sophie2220** [Pitt-CSC/Summer2021-Internships#25]

**Comment by harshraj22** [comment]
It seems it has been added.

**Comment by sophie2220** [comment]
Yes, I meant that it should not be included on this list because it is not a summer 2021 position, right?

**Comment by Zmwang622** [comment]
I think it's for summer 2021? the date posted was in the year 2929

**Comment by sophie2220** [comment]
Yeah I was confused too but if you click on any of the 4 positions it says: "This position will begin in the summer of 2020 and lasts approximately 10 weeks". Maybe it's a typo on their end?

**Comment by Zmwang622** [comment]
I think it's a typo.. we can wait and see
