### ISSUE TITLE
GL_INVALID_FRAMEBUFFER_OPERATION on fullscreen

### ISSUE THREAD

**Issue by Voxol** [Pitt-CSC/Summer2021-Internships#261]
When F11 is hit and it goes in fullscreen mode, functionality works but error GL_INVALID_FRAMEBUFFER_OPERATION is spammed in the console

**Comment by Zmwang622** [comment]
I don't know what that means/how we could remedy taht

**Comment by Voxol** [comment]
LOL sorry wrong tab

**Comment by Zmwang622** [comment]
all good
