### ISSUE TITLE
Coursera Internship Has Link Expired

### ISSUE THREAD

**Issue by azimjohn** [Pitt-CSC/Summer2021-Internships#268]
<img width="967" alt="Screen Shot 2020-10-15 at 20 08 16" src="https://user-images.githubusercontent.com/35038240/96169311-3a848480-0f22-11eb-9ab9-b45c46947b1c.png">

**Comment by GintasS** [comment]
@Zmwang622 Is this the case of them opening/closing the application or did they really have removed the posting?

**Comment by azimjohn** [comment]
They probably have removed the posting.

**Comment by Zmwang622** [comment]
Looks like it's removed from their job page: https://jobs.lever.co/coursera/
