### ISSUE TITLE
Add automatic link checker for this repository

### ISSUE THREAD

**Issue by GintasS** [Pitt-CSC/Summer2021-Internships#273]
https://github.com/marketplace/actions/markdown-link-check 

If this would not work, I think we could find similar solutions.

This is a Github action that would periodically scan for dead links, so that we could see internships that are closed faster. Maybe this would allow to add an issue automatically with the dead links?

Yes, this solution is not 100% bulletproof, since links change, redirects are possible, and in a lot of cases companies put a text "We are no longer accepting applications" instead of decommissioning a link.

**Comment by Zmwang622** [comment]
I think the issue we have with postings closing isn't that they aren't dead, they just lead to a link that says posting closed. I might not be completely understanding the action but I think it'd only check if a link works or not right?

**Comment by GintasS** [comment]
> I think the issue we have with postings closing isn't that they aren't dead, they just lead to a link that says posting closed. I might not be completely understanding the action but I think it'd only check if a link works or not right?

For the most part, you're right, they do only check if a link works, but just today, using a plugin from VSC I deleted 21 internships that were caught with a similar tool, these links returned a non 200 status. So this might still be worth to investigate, especially if you can add it as a process.

**Comment by Zmwang622** [comment]
Oh taht's awesome, what's the plugin? I think in that case it's totally worth investigating

**Comment by GintasS** [comment]
Here you go: [link](https://marketplace.visualstudio.com/items?itemName=blackmist.LinkCheckMD) but this done manually, it just gets you the links, my suggestion to automate this with a similar github action above.

**Comment by Zmwang622** [comment]
alright ill look into it once i have some time

**Comment by GintasS** [comment]
@Zmwang622 any news, this would be really cool to have, to remove some postings automatically.

**Comment by Zmwang622** [comment]
@GintasS I haven't found to look into it (busy with school :/). If you wanna take a crack at it go for it!

**Comment by GintasS** [comment]
@Zmwang622 It's ok, I'm bit too busy atm, so not sure.

**Comment by GintasS** [comment]
Been experimenting for a bit this weekend, I've created a dummy repo: https://github.com/GintasS/Markdown-link-check-test with internship links from there and ran the markdown-link action, you can see it produces results (but still fails, I don't know why). Incorporating it with automatic issue creation or an email sender would be great.

**Comment by Zmwang622** [comment]
Yeah that's interesting. Where is your code? I'll try and implement something this weekend, maybe..

**Comment by GintasS** [comment]
There is no code, this is a [GitHub Action](https://github.com/features/actions), it can be set up with .yml file, you can add it like a cron job. Adding some sort of automatic issue creation like [this](https://github.com/marketplace/actions/oction-create-issue) this could help a LOT, but not sure how to integrate all of this :D

**Comment by Zmwang622** [comment]
oooh cool yeah that makes sense

**Comment by GintasS** [comment]
Probably should close this, no?

**Comment by Zmwang622** [comment]
I guess, one day i will get to it
