### ISSUE TITLE
Potentially broken links

### ISSUE THREAD

**Issue by GintasS** [Pitt-CSC/Summer2021-Internships#283]
Some of these links are potentially broken and needs replacing:
Ran with HTTP/s and relative link checker tool. https://marketplace.visualstudio.com/items?itemName=blackmist.LinkCheckMD

- Error: https://www.citadel.com/careers/open-positions/positions-for-students/ on line 19 is unreachable.
- Error: https://motorolasolutions.zrapply.com/en-US/Careers/job/Schaumburg-IL/Software-Engineer_R7477?utm_source=PittCSC on line 81 is unreachable.
- Error: https://jobs.bnymellon.com/jobs/2007833 on line 80 is unreachable.
- Error: https://www.janestreet.com/join-jane-street/position/4787572002/ on line 32 is unreachable.
- Error: https://jobszp1.lanl.gov/OA_HTML/OA.jsp?page=/oracle/apps/irc/candidateSelfService/webui/VisVacDispPG&OAHP=IRC_EXT_SITE_VISITOR_APPL&OASF=IRC_VIS_VAC_DISPLAY&akRegionApplicationId=821&transactionid=1759536200&retainAM=N&addBreadCrumb=RP&p_svid=81425&p_spid=3628350 on line 71 is unreachable.
- Error: https://www.toyotaconnected.com/job?gh_jid=4421992002&did=4040990002 on line 130 is unreachable.
- Error: https://careers.point72.com/CSJobDetail?jobName=2021-cubist-software-engineering-internship-program&jobCode=CSS-0004136 on line 146 is unreachable.
- Error: https://dell.wd1.myworkdayjobs.com/ExternalNonPublic/job/Austin-Texas-United-States/Undergraduate-Intern--Software-Engineer_R068404 on line 140 is unreachable.
- Error: https://jobs.lever.co/anduril/7ccb543a-a233-4db9-8c1e-1cb8e5b27cd4?utm_source=PittCSC on line 143 is unreachable.
- Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?PageType=JobDetails&partnerid=25239&siteid=5014&jobid=6674182#jobDetails=6674182_5014 on line 167 is unreachable.
- Error: https://careers.icims.com/jobs/22732? on line 192 is unreachable.
- Error: https://boards.greenhouse.io/memsql/jobs/2328598 on line 202 is unreachable.
- Error: https://careers.viasat.com/careers/FolderDetail/Software-Engineer-Intern/5765 on line 221 is unreachable.
- Error: https://jobs.intel.com/page/show/search-results#q=2021&t=Jobs&sort=relevancy&layout=table&f:@countryfullname=[United%20States]&f:@employeetype=[Intern%2FStudent] on line 259 is unreachable.
- Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25385&siteid=5311&PageType=searchResults&SearchType=linkquery&LinkID=3974233#jobDetails=496624_5311 on line 243 is unreachable.
- Error: https://careers.steelcase.com/external/FolderDetail/Hedberg-IT-Intern-Summer-2021/2896 on line 325 is unreachable.
- Error: https://careers.steelcase.com/external/FolderDetail/Advanced-Analytics-Intern-Summer-2021/2882 on line 325 is unreachable.
- Error: https://career.bayer.us/en/job/pharmacovigilance-data-science-intern-summer-2021--SF263524 on line 313 is unreachable.
- Error: https://careers.caci.com/ListJobs?keyword=2021&&Page=1&SortOrder=desc&SortField=AddedOn on line 326 is unreachable.
- Error: https://www.hitachiabb-powergrids.com/career/open-jobs?filter-search=2021&filter-country=US&filter-page=1 on line 347 is unreachable.
- Error: https://cg.sandia.gov/psc/applicant/EMPLOYEE/HRMS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Page=HRS_APP_SCHJOB_FL&Action=U on line 352 is unreachable.
- Error: https://app.hiremojo.com/mojo/ce/484522943/DISTek-Integration-Inc/Iowa/Cedar-Falls/Engineer#/ on line 370 is unreachable.
- Error: https://jobs.gsk.com/en-us/jobs/263689?lang=en-us&previousLocale=en-US on line 385 is unreachable.
- Error: https://careers.petsmart.com/student-interns/jobs?keywords=Software&page=1&sortBy=relevance&categories=Students on line 392 is unreachable.
- Error: https://www.xylem.com/en-lt/careers/career-opportunities?page=1&pagesize=96&keyword=2021 on line 394 is unreachable.
- Error: https://careers.perspecta.com/jobs?keywords=2021&page=1 on line 402 is unreachable.
- Error: https://jobs.comcast.com/jobs/description/regular?job_id=221340&external_or_internal=external on line 406 is unreachable.
- Error: https://www.bms.com/ca/en/job-seekers/job-search-results.html?country=united%20states%20of%20america&category=intern/co-op/student/flex&keyword=2021&page=1 on line 403 is unreachable.
- Error: https://www.ga-careers.com/job/san-diego/internship-software-engineering-summer-2021/499/1925884416 on line 453 is unreachable.
- Error: https://bairdcareers.com/career-search/?keyword=2021&zip=&distance=20.0&country=United%20States%20of%20America&state=&office=&career_areas=&spage=1 on line 455 is unreachable.

**Comment by Zmwang622** [comment]
will look into it tomorrow morning

**Comment by Zmwang622** [comment]
alright went through them some are broken but most are fine. I think if we implemented the auto link checker it'd prob have to do something where it just sends email notifications of potentially broken links.

**Comment by GintasS** [comment]
Thanks, yes, or just post them in a new issue for us to remove.
