### ISSUE TITLE
Internships that have website problems

### ISSUE THREAD

**Issue by GintasS** [Pitt-CSC/Summer2021-Internships#289]
Should we add internships like these:

|[Expedition Technology](https://www.exptechinc.com/pages/careers/)| Herndon, VA | US Citizenship is a requirement for these positions due to US Government rules regarding security clearances. |

Where websites have problems with certificates and it warns user to not trust the website and don't put any personal data into it. Should we add companies like these, do we care about it at all?

**Comment by Zmwang622** [comment]
Sorry forgot to respond! I say we should pass on those. We already have so many postings haha
