### ISSUE TITLE
Amazon Link

### ISSUE THREAD

**Issue by samjoffe** [Pitt-CSC/Summer2021-Internships#29]
Link doesn't work because you didn't add the http://. However, entering it manually it is still an invalid link.

This link https://amzn-sp.com/3hCEKwz seems to work tho? But haven't seen an official announcement that they're open.

**Comment by Zmwang622** [comment]
yeah so i think it's invite-only, and people with the NSBE link are invited which explains why it works.

**Comment by cjmaria** [comment]
If this link is to be on this repo at all, it should at least have a note saying that it was intended for NSBE members. The ethics of applying to a posting that you weren't invited to are questionable and people should know where this came from so they can make that judgement themselves.

**Comment by Zmwang622** [comment]
Agreed, im going to remove the posting

**Comment by zejunliu** [comment]
Damn, I just applied for this position without taking a careful look…. Hope it won’t cause any trouble for me…..😂

**Comment by Zmwang622** [comment]
you'll be fine, but tbh just oversight on my part, so if you get in trouble just blame it on me lolol

**Comment by samjoffe** [comment]
^ Same. I withdrew the application because I didn't realize that either. Hopefully the normal posting uses a different job ID, but if not, I guess I learned an important lesson.

**Comment by zejunliu** [comment]
I was wondering why I could not see it on job postings of amazon websites… lol

**Comment by miraliahmadli** [comment]
I can open the link without invitation. I did not get what is the issue?

**Comment by ShreyasKudari** [comment]
I submitted my app and withdrew after reading this. If the job ID is the same when the official posting comes out maybe its possible to email them and reset the application.
