### ISSUE TITLE
Open to International Students?

### ISSUE THREAD

**Issue by saint1729** [Pitt-CSC/Summer2021-Internships#295]
Hi @Pitt-CSC,

Are all the companies listed here open to both US Citizens and International Students? If not, can we add a column for that?

**Comment by benyam7** [comment]
Yes, please! this was a pain in the ass for me. @Pitt-CSC

**Comment by Zmwang622** [comment]
I prefer we not make it another column because the table wouldn't look as good, but if there are postings that aren't available for international students make a PR to add it to the notes!
