### ISSUE TITLE
Vanguard link is for Summer 2020

### ISSUE THREAD

**Issue by SahasGoli** [Pitt-CSC/Summer2021-Internships#30]
Opening up the job postings for vanguard they explicitly say "This program is available in both PA and NC. This position will begin in the summer of 2020 and lasts approximately 10 weeks"

**Comment by Zmwang622** [comment]
See #25

**Comment by SahasGoli** [comment]
Oops, sorry.

**Comment by Zmwang622** [comment]
No worries! So I think the posting is for summer 2021 because it was posted last month. We'll just wait and see for now
