### ISSUE TITLE
Coursera Internship

### ISSUE THREAD

**Issue by epicmanmoo** [Pitt-CSC/Summer2021-Internships#43]
Link to Coursera 2021 Summer Internship is broken: https://jobs.lever.co/coursera/79db349e-159d-4697-bdd6-b292011a9ce3
Hopefully it's fixed later today.

**Comment by Zmwang622** [comment]
it works for me?

**Comment by epicmanmoo** [comment]
Wow, that was quick. Looks like it was down for a bit.!

**Comment by tuankiet65** [comment]
404 again, they probably took it down permanently.

**Comment by Zmwang622** [comment]
works for me?

**Comment by tuankiet65** [comment]
Works on my side now, that's weird :/

**Comment by Zmwang622** [comment]
Yeah its opens and closes often
