### ISSUE TITLE
Bessemer Venture Partners Fellowship Program is Closed

### ISSUE THREAD

**Issue by Maanav-G** [Pitt-CSC/Summer2021-Internships#58]
Even though the TypeForm is still up, I don't believe they're accepting any more applicants: 
1. "...the interviews will take place in mid to late August..." 
2. I applied earlier in May/June and I received the email to set-up my final interview around late June

**Comment by Zmwang622** [comment]
What was the interview process like? Have my first round this week

**Comment by Maanav-G** [comment]
> What was the interview process like? Have my first round this week

Couldn't say - I have my first round tomorrow
