### ISSUE TITLE
MLH Fellowships (not exactly "internships")?

### ISSUE THREAD

**Issue by zhixiangteoh** [Pitt-CSC/Summer2021-Internships#67]
https://fellowship.mlh.io/

https://news.mlh.io/the-mlh-fellowship-is-back-this-fall-08-12-2020#:~:text=Applications%20are%20open%20now%20at,applicants%20from%20around%20the%20world.

**Comment by Zmwang622** [comment]
looks good to me, make a PR and I'll merge it
