### ISSUE TITLE
Workiva New Link

### ISSUE THREAD

**Issue by samjoffe** [Pitt-CSC/Summer2021-Internships#74]
https://workiva.wd1.myworkdayjobs.com/en-US/careers/job/Scottsdale/Summer-2021---Software-Engineering-Intern_R560

The earlier posting was removed due to not asking all the questions they wanted answered. All applicants were sent the above new link to reapply (and people can apply for the first time with it as well).

**Comment by Zmwang622** [comment]
thanks beast
