### ISSUE TITLE
Qualtrics Seattle SWE Link Broken

### ISSUE THREAD

**Issue by zhixiangteoh** [Pitt-CSC/Summer2021-Internships#82]
https://www.qualtrics.com/careers/us/en/job/151240/Software-Engineering-Intern-Summer-2021-Seattle-WA?utm_source=PittCSC

**Comment by zejunliu** [comment]
Does anyone have trouble applying for Microsoft  internship? I always get 502 bad getway warning.

**Comment by aidev1065** [comment]
Yup! It's a problem with their servers

**Comment by aidev1065** [comment]
It's been fixed
